sdk adapted for working with new API
ConcoMB/arena-tools pull request #3
Opened 2023-03-03 12:30 UTC by fermartin17

2023-03-03 12:54 UTC, ConcoMB commented on lib/arena-tools.js
> +const API_URL = 'http://localhost:8080/';
is this intentional?

2023-03-03 18:16 UTC, ConcoMB requested changes

2023-03-03 18:16 UTC, ConcoMB commented on lib/arena-tools.js
>  "use strict";
@fermartin17 borra esto de git si lo agregaste al ignore.

2023-03-06 11:55 UTC, fermartin17 commented on lib/arena-tools.js
>  "use strict";
ya lo borro

2023-03-07 17:41 UTC, ConcoMB approved these changes

2023-03-07 17:42 UTC, merged